name: Generate Codebase Tree

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-tree:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 4: Run the Go script
      - name: Run generate tree script for codebase
        run: go run main.go

      # Step 5: Verify generated file structure
      - name: Debug - List files before commit
        run: ls -R
      
      # Step 6: Commit and push changes (force-add new files)
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add --force *  # Force add all files including ignored ones
          if [ "$(git status --porcelain)" ]; then
            git commit -m "Update codebase tree structure [skip ci]"
            git push
          else
            echo "No changes detected, skipping commit."
          fi
