name: Generate Codebase Tree

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-tree:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      # Step 3: Install dependencies (if any)
      # - name: Install dependencies
        # run: go mod tidy

      # Step 4: Run the Go script
      - name: Run generate tree script for code-base
        run: go run main.go

      # Step 5: Commit and push changes (if README.md was updated)
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "Update codebase tree structure [skip ci]"
            git push
          fi
